name: Post-Template Initialization

on:
  push:
    branches:
      - main  # atau master

jobs:
  setup:
    # Hanya berjalan sekali saat repo baru dibuat dari template
    if: github.repository != 'username-lu/nama-repo-template-asal'
    runs-on: ubuntu-latest
    permissions:       
      contents: write 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Rename Placeholders
        run: |
          # Mengambil nama repo baru
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          
          # Cari dan ganti placeholder {{PROJECT_NAME}} di file yang ditentukan
          sed -i "s/{{PROJECT_NAME}}/$REPO_NAME/g" package.json
          sed -i "s/{{PROJECT_NAME}}/$REPO_NAME/g" README.md

      - name: Clean up workflow
        run: |
          # Hapus workflow ini biar ga jalan lagi di push berikutnya
          rm .github/workflows/post-create.yml

      - name: Commit & Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Initialize repository from template"
          git push
